grammyjs/types

inline.d.ts, manage.d.ts, message.d.ts, proxied.d.ts
Title says it all.
https://core.telegram.org/bots/api#december-7-2021
=> Update to Bot API 5.5

manage.d.ts
=> Narrow down ChatJoinRequest['chat']

manage.d.ts, message.d.ts, proxied.d.ts
Title says it all, see https://t.me/BotNews/77
=> Update to Bot API 6.3

update.d.ts
As announced in https://t.me/grammyjs/100772
=> feat: narrow message updates

manage.d.ts, markup.d.ts, message.d.ts, proxied.d.ts
https://core.telegram.org/bots/api#december-30-2022
=> feat: add support for Bot API 6.4

manage.d.ts, markup.d.ts, message.d.ts, proxied.d.ts
https://core.telegram.org/bots/api#february-3-2023
=> feat: support Bot API 6.5

inline.ts, manage.ts, markup.ts, message.ts, methods.ts, settings.ts
https://core.telegram.org/bots/api#april-21-2023
=> Update to Bot API 6.7

manage.ts, message.ts, methods.ts
https://core.telegram.org/bots/api#august-18-2023
=> feat: update to Bot API 6.8

.vscode/settings.json, api.ts, deno.jsonc, inline.ts, manage.ts, markup.ts, message.ts, methods.ts, update.ts
https://core.telegram.org/bots/api#december-29-2023
=> feat: Bot API 7.0

manage.ts, message.ts, methods.ts
https://core.telegram.org/bots/api#february-16-2024
=> feat: support Bot API 7.1

manage.ts, markup.ts, message.ts, methods.ts, passport.ts, update.ts
https://core.telegram.org/bots/api#march-31-2024
=> feat: support Bot API 7.2

markup.ts, methods.ts, payment.ts
https://core.telegram.org/bots/api#june-18-2024
=> feat: support Bot API 7.5

manage.ts, message.ts, methods.ts, payment.ts, settings.ts
https://core.telegram.org/bots/api#july-1-2024
=> feat: support Bot API 7.6

message.ts, payment.ts
https://core.telegram.org/bots/api#july-7-2024
=> feat: support Bot API 7.7

manage.ts
=> fix: ChatFullInfo.title for groups, supergroups and channels

manage.ts, methods.ts
https://core.telegram.org/bots/api#july-31-2024
=> feat: support Bot API 7.8

manage.ts, message.ts, methods.ts, payment.ts
https://core.telegram.org/bots/api#august-14-2024
=> feat: support Bot API 7.9

manage.ts, message.ts, methods.ts, payment.ts, update.ts
https://core.telegram.org/bots/api#september-6-2024
=> feat: support Bot API 7.10

markup.ts, message.ts, methods.ts, payment.ts
https://core.telegram.org/bots/api#october-31-2024
=> feat: support Bot API 7.11

message.ts, methods.ts, payment.ts
https://core.telegram.org/bots/api#november-17-2024
=> feat: support Bot API 8.0

payment.ts
https://core.telegram.org/bots/api#december-4-2024
=> feat: support Bot API 8.1

methods.ts
This makes sure that all functions have exactly one parameter
=> refactor: make all function signatures consistent

inline.ts, manage.ts, message.ts, methods.ts, payment.ts
https://core.telegram.org/bots/api#january-1-2025
=> feat: support Bot API 8.2

manage.ts, message.ts, methods.ts, payment.ts
https://core.telegram.org/bots/api#february-12-2025
=> feat: support Bot API 8.3

manage.ts, message.ts, methods.ts, mod.ts, payment.ts, story.ts
https://core.telegram.org/bots/api#april-11-2025
=> feat: support Bot Api 9.0

manage.ts, markup.ts, message.ts, methods.ts, payment.ts, settings.ts
https://core.telegram.org/bots/api#august-15-2025
=> feat: support Bot API 9.2

message.ts
=> fix: add `entities` property to `TextMessage` type
